# Раздел 1. Как вообще этим пользоваться?

In [1]:
123+3211 #Это ячейка с кодом

3334

Это ячейка с Markdown разметкой
 - Первый пункт
 - Второй пункт
 - Третий пункт

In [2]:
print 1
2
print 3

1
3


In [3]:
!echo "Начиная строку с восклицательного знака можно выполнять консольные команды!"

Начиная строку с восклицательного знака можно выполнять консольные команды!


In [4]:
# Используйте Tab для подсказок путей и Python методов
# Большой вывод ячейки можно скрыть двойным или тройным щелчком
!ls /usr/bin/

[				    mattrib
2to3				    mawk
2to3-2.7			    mbadblocks
2to3-3.5			    mboximporter
411toppm			    mc
4xml				    mcat
4xpath				    mcd
4xslt				    mcdiff
4xupdate			    mcedit
7z				    mcheck
7za				    mclasserase
a11y-profile-manager-indicator	    mcomp
a2ping				    mcookie
a5toa4				    mcopy
aa-enabled			    mc-tool
accountwizard			    mcview
aclocal				    mc-wait-for-name
aclocal-1.15			    md5sum
aconnect			    md5sum.textutils
acpi_listen			    mdatopbm
activity-log-manager		    mdel
acyclic				    mdeltree
add-apt-repository		    mdir
addpart				    mdu
addr2line			    meinproc4
adhocfilelist			    meinproc4_simple
aeskulap			    meinproc5
afm2afm				    melt
afm2pl				    mendex
afm2tfm				    mesg
aj				    meshlab
aj5				    meshlabserver
ajbrowser			    mf
ajc				    mf2pt1
ajdoc				    mf-nowin
akonadi_agent_launcher		    mformat
akonadi_agent_server		    mfplain
akonadi_akonotes_resource	    mft
akonadi_archivemail_agent	    mgrtopbm
akonadi_baloo_indexer		    m

In [5]:
# Вот так можно смешивать код Python и консоли. Но я не рекомендую!
for i in range(3):
    !echo {i+1}

1
2
3


In [6]:
#Стандартный вызов справки
help(file)

Help on class file in module __builtin__:

class file(object)
 |  file(name[, mode[, buffering]]) -> file object
 |  
 |  Open a file.  The mode can be 'r', 'w' or 'a' for reading (default),
 |  writing or appending.  The file will be created if it doesn't exist
 |  when opened for writing or appending; it will be truncated when
 |  opened for writing.  Add a 'b' to the mode for binary files.
 |  Add a '+' to the mode to allow simultaneous reading and writing.
 |  If the buffering argument is given, 0 means unbuffered, 1 means line
 |  buffered, and larger numbers specify the buffer size.  The preferred way
 |  to open a file is with the builtin open() function.
 |  Add a 'U' to mode to open the file for input with universal newline
 |  support.  Any line ending in the input file will be seen as a '\n'
 |  in Python.  Also, a file so opened gains the attribute 'newlines';
 |  the value for this attribute is one of None (no newline read yet),
 |  '\r', '\n', '\r\n' or a tuple containing

In [7]:
#Вызов справки через IPython
?file

# Раздел 2. Основы магии

In [8]:
#Длинная справка
%magic

In [9]:
#Короткая справка
%quickref

In [10]:
#Справка по команде
%run?

In [1]:
# Магия run запускает внешние скрипты
%run run_me.py

Hello everybody!


In [16]:
# Магия run может запускать другие блокноты на исполнение доконца
%run psutils_tutorial.ipynb

ImportError: No module named psutil

In [17]:
# Эта магия узнает о загруженных переменных
%whos

Variable   Type    Data/Info
----------------------------
i          int     2


In [14]:
# Эта магия достает историю
%hist

123+3211 #Это ячейка с кодом
print 1
2
print 3
!echo "Начиная строку с восклицательного знака можно выполнять консольные команды!"
# Используйте Tab для подсказок путей и Python методов
# Большой вывод ячейки можно скрыть двойным или тройным щелчком
!ls /usr/bin/
# Вот так можно смешивать код Python и консоли. Но я не рекомендую!
for i in range(3):
    !echo {i+1}
#Стандартный вызов справки
help(file)
#Вызов справки через IPython
?file
#Длинная справка
%magic
#Короткая справка
%quickref
#Справка по команде
%run?
# Магия run запускает внешние скрипты
%run run_me.py
# Магия run может запускать другие блокноты на исполнение доконца
%run psutils_tutorial.ipynb
# Эта магия узнает о загруженных переменных
%whos
# Эта магия достает историю
%hist


In [15]:
#Часть консольных команд дублирована в виде магии!
%ls
%pwd

foo.py         import_me.pyc              run_me.py
general.ipynb  matplotlib_tutorial.ipynb  time_measurements.ipynb
import_me.py   psutils_tutorial.ipynb     widgets.ipynb


u'/home/kostanew/Documents/comp_sci_spring_2017/lesson1'

# Раздел 3. Импорт в Python

In [2]:
#Вспомним об импорте в Python вообще
import numpy
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [4]:
from numpy import array
array([1,2,3])

array([1, 2, 3])

In [7]:
!cat import_me.pyc


L�Xc@s
dZdS(iN(tmy_variable(((simport_me.pyt<module>s

In [6]:
import import_me

In [8]:
import_me.__file__

'import_me.pyc'

In [9]:
dir(import_me)

['__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 'my_variable']

In [12]:
import_me.my_variable

1

In [13]:
# Теперь поменяйте число в файле import_me.py и выполните ячейку
import import_me
import_me.my_variable

1

Важные свойства импорта:
- По умолчанию импорт происходит один раз
- Поведение модуля такое же как у Синглтона!

# Раздел 4. Особенности импорта в Python

In [23]:
# Эта магия позволит вам подгружать ваши файлы каждый раз заново
%load_ext autoreload
%autoreload 1

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
import import_me
import_me.my_variable

1

Почему это важно?

Иногда нужно скомпоновать большие классы и блокноты. Динамический импорт позволит вам делать это УДОБНО!

# Раздел 5. Информация о системе

In [25]:
import IPython
print IPython.sys_info()

{'commit_hash': u'5c9c918',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/dist-packages/IPython',
 'ipython_version': '5.1.0',
 'os_name': 'posix',
 'platform': 'Linux-4.4.0-62-generic-x86_64-with-Ubuntu-16.04-xenial',
 'sys_executable': '/usr/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.12 (default, Nov 19 2016, 06:48:10) \n[GCC 5.4.0 20160609]'}


In [26]:
%load_ext watermark
%watermark?

In [27]:
%watermark

2017-02-22T18:31:17

CPython 2.7.12
IPython 5.1.0

compiler   : GCC 5.4.0 20160609
system     : Linux
release    : 4.4.0-62-generic
machine    : x86_64
processor  : x86_64
CPU cores  : 8
interpreter: 64bit


In [28]:
numpy.__version__

'1.11.3'