In [6]:
type([]), type('123'), type(123)

(list, str, int)

In [7]:
import numpy as np

In [8]:
data = np.ones((4,5,6))

In [10]:
data.shape

(4, 5, 6)

In [11]:
data.ravel()

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [16]:
data.ndim

3

In [14]:
data.size

120

In [17]:
data.dtype

dtype('float64')

In [20]:
ch_arr = np.chararray(10, itemsize='4')
ch_arr

chararray(['', '', '\x00d\x01', 'd\x02\x00\x83', '\x01\x01Z\x02', '\x00d\x03',
       'S\x900\x01', '', '0', ''], 
      dtype='|S4')

In [21]:
ch_arr = np.chararray(['1', '2', '4'])
ch_arr

TypeError: an integer is required

In [22]:
x = np.array([(1,2.,'Hello'), (2,3.,"World")],
             dtype=[('foo', 'i4'),('bar', 'f4'), ('baz', 'S10')])
x


array([(1, 2.0, 'Hello'), (2, 3.0, 'World')], 
      dtype=[('foo', '<i4'), ('bar', '<f4'), ('baz', 'S10')])

In [23]:
x[0]

(1, 2.0, 'Hello')

In [24]:
x['foo']

array([1, 2], dtype=int32)

In [32]:
data = np.loadtxt('data4read.csv')
data

array([[ 1.,  2.,  3.],
       [ 1.,  3.,  2.],
       [ 2.,  1.,  3.],
       [ 2.,  3.,  1.],
       [ 3.,  1.,  2.],
       [ 3.,  2.,  1.]])

In [33]:
data = np.loadtxt('data4read.csv', dtype=[('A', int),('B', int), ('C', float)])
data

array([(1, 2, 3.0), (1, 3, 2.0), (2, 1, 3.0), (2, 3, 1.0), (3, 1, 2.0),
       (3, 2, 1.0)], 
      dtype=[('A', '<i8'), ('B', '<i8'), ('C', '<f8')])

In [35]:
np.save('test_output.npy', data)
np.load('test_output.npy')

array([(1, 2, 3.0), (1, 3, 2.0), (2, 1, 3.0), (2, 3, 1.0), (3, 1, 2.0),
       (3, 2, 1.0)], 
      dtype=[('A', '<i8'), ('B', '<i8'), ('C', '<f8')])

In [42]:
np.savez('test_output.npz', X=data, Y=data)
recovery = np.load('test_output.npz')
recovery['X'], recovery['Y']

(array([(1, 2, 3.0), (1, 3, 2.0), (2, 1, 3.0), (2, 3, 1.0), (3, 1, 2.0),
        (3, 2, 1.0)], 
       dtype=[('A', '<i8'), ('B', '<i8'), ('C', '<f8')]),
 array([(1, 2, 3.0), (1, 3, 2.0), (2, 1, 3.0), (2, 3, 1.0), (3, 1, 2.0),
        (3, 2, 1.0)], 
       dtype=[('A', '<i8'), ('B', '<i8'), ('C', '<f8')]))